#! /bin/bash

set -e -o pipefail

function initial_setup() {
    echo "=== Performing initial Claude setup ==="

    # MCP servers
    claude mcp add --transport stdio context7 -- npx -y @upstash/context7-mcp
    claude mcp add --transport stdio docling -- uvx --from=docling-mcp docling-mcp-server --transport stdio
    claude mcp add --transport stdio playwright -- npx -y @playwright/mcp --headless --isolated

    # Plugins
    claude plugin marketplace add obra/superpowers-marketplace
    claude plugin install superpowers@superpowers-marketplace
}


cd "${HOME}/workspace"

if [ ! -d "${HOME}/.claude" ]; then  # 1st run
    initial_setup
else
    claude plugin marketplace update
fi

exec claude --allow-dangerously-skip-permissions "$@"
